# Minimal Investor Pitch & Deck Generator scaffold (Flask)
# Save as server.py
# NOTES:
# - Replace OPENAI_API_KEY with your key or configure PERPLEXITY_API_KEY if you use Perplexity APIs.
# - This scaffold uses OpenAI-style calls as an example; swap for Perplexity client if available.

import os
import io
import json
from flask import Flask, request, jsonify, send_file
from dotenv import load_dotenv
import pandas as pd
from pptx import Presentation
from pptx.util import Inches, Pt
import openai  # example; swap with Perplexity client if available

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
openai.api_key = OPENAI_API_KEY

app = Flask(__name__)

def generate_pitch_text(company_name, target_raise, tone="professional", inputs=None):
    # Simple LLM call example — replace prompt template as needed
    prompt = f"""You are an expert startup advisor. Create a concise investor pitch for {company_name}.
Target raise: {target_raise}.
Tone: {tone}.
Include: 1-page executive summary, 6-8 slide titles with short speaker notes, 3-year high-level financial assumptions.
Inputs: {json.dumps(inputs) if inputs else 'none'}.
"""
    resp = openai.ChatCompletion.create(
        model="gpt-4o-mini",  # replace with your chosen model
        messages=[{"role":"user","content":prompt}],
        max_tokens=800
    )
    return resp["choices"][0]["message"]["content"]

def create_deck_from_text(pitch_text, out_path="pitch_deck.pptx", company_name="Company"):
    prs = Presentation()
    # Title slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = f"{company_name} — Investor Pitch"
    subtitle.text = "Generated by Investor Pitch Skill"

    # Split pitch_text into slide blocks heuristically
    sections = pitch_text.split("\n\n")
    for sec in sections:
        if len(sec.strip()) == 0: 
            continue
        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)
        title = slide.shapes.title
        body = slide.shapes.placeholders[1].text_frame
        lines = sec.strip().split("\n")
        title.text = lines[0][:60]
        body.text = "\n".join(lines[1:])[:1000]

    prs.save(out_path)
    return out_path

@app.route("/generate", methods=["POST"])
def generate():
    """
    POST /generate
    JSON body:
    {
      "company_name": "Acme",
      "target_raise": "2,000,000",
      "tone": "investor-friendly",
      "financials_csv": "<base64 or omitted>",
      "assumptions": {"growth":0.3, "margin":0.18}
    }
    Returns: JSON with generated_text and link to PPTX
    """
    data = request.get_json()
    company_name = data.get("company_name", "Unnamed Co")
    target_raise = data.get("target_raise", "unspecified")
    tone = data.get("tone", "professional")
    inputs = {
        "assumptions": data.get("assumptions", {}),
        "notes": data.get("notes", "")
    }

    # Optionally process uploaded CSV (if included)
    # For simplicity this scaffold does not implement file upload; but you can accept multipart/form-data in production
    pitch_text = generate_pitch_text(company_name, target_raise, tone, inputs)
    pptx_path = create_deck_from_text(pitch_text, out_path=f"{company_name}_pitch_deck.pptx", company_name=company_name)

    return jsonify({
        "company_name": company_name,
        "pitch_text": pitch_text,
        "pptx_file": pptx_path
    })

@app.route("/download/<path:filename>", methods=["GET"])
def download(filename):
    return send_file(filename, as_attachment=True)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.getenv("PORT", 8080)))
